# Generated by Django 4.0 on 2021-12-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
