# Generated by Django 4.0 on 2021-12-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wins',
        ),
    ]
