# Generated by Django 4.0 on 2021-12-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='player',
            new_name='user',
        ),
    ]
