# Generated by Django 4.0 on 2021-12-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe_game', '0002_alter_game_current_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('id',)},
        ),
    ]
