# Generated by Django 4.0 on 2021-12-16 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_wins'),
        ('tictactoe_game', '0003_alter_game_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='won',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='won_games', to='accounts.user'),
        ),
        migrations.AddConstraint(
            model_name='move',
            constraint=models.UniqueConstraint(fields=('x', 'y', 'game'), name='only_one_move_per_game'),
        ),
    ]
